riverside_pt.settings:
  type: config_object
  label: 'Riverside PT Settings'
  mapping:
    notification_email:
      type: string
      label: 'Notification email address'
    holidays:
      type: sequence
      label: 'Holidays'
      sequence:
        type: mapping
        label: 'Holiday'
        mapping:
          date:
            type: string
            label: 'Date (YYYY-MM-DD)'
          name:
            type: string
            label: 'Holiday name'
